spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
